language: python

before_install:
  - sudo apt-get update
  - pip install -U pip

python:
  - "3.5"
  - "3.6"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - python -m nltk.downloader stopwords


#services and databases
services:
  - mongodb

# command to run tests
script: py.test
